### ISSUE TITLE
Allow images with relative paths to be displayed in README

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#211]
When an image in a README uses a relative path, e.g.

`<img src="images/time_series_hdfview.png" width=400/>`

in https://raw.githubusercontent.com/OpenSourceBrain/NWBShowcase/master/README.md

 on GitHub the image displays fine, but not in the Readme summary on OSBv2. 
https://v2dev.opensourcebrain.org/repositories/2

Any issue with appending the repo URL to these @Muhaddatha?

**Comment by filippomc** [comment]
@pgleeson we initially made an implementation of this but ended up being not very robust so we removed it.
It's not exactly the repository url that we need to append, it's the "raw.github..." so we need to do a replacement. That would be fine if github were the only source of repositories, but we want to write the code so that we don't need to redo stuff when other repository type are implemented
