### ISSUE TITLE
Repositories: link to the commit they were created from?

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#335]
For repos, should we link to the commit they were created from so that when the user views the repository, they see the same contents?

**Comment by pgleeson** [comment]
It doesn't matter what the commit was when the repo was created (by design), only the branch/repo source. A repo's contents can always change and the current state is reflected in the listing on OSB, and what is initially used for populating the workspace. 

What should be noted somewhere is the specific commit used to generate a **workspace**. That is best recorded in the "history file" in https://github.com/OpenSourceBrain/OSBv2/issues/210. Note too though that not all files are copied into a workspace necesarily, so it won't really reflect "the exact state of the repository at that commit", just a subset of files as they were in that commit.

**Comment by sanjayankur31** [comment]
Sounds good, closing this since #210 already notes the workspace history bit
