### ISSUE TITLE
Should the repository URL and name be modifiable after it has been created?

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#338]
Currently, clicking the "Edit" button for repositories also allows users to modify the source URL and it's name.
Should this be permitted? I guess the tags/type and description are probably OK to change, but should the source and name be modifiable?

Changing these makes it a brand new repository.

For example, I edited my SolinasEtAl repository to update the GitHub URl to github.com/NeuroML/NeuroML2, and now it's a NeuroML repository.. Feels a bit weird..

@pgleeson : what do you think?

**Comment by sanjayankur31** [comment]
Additional question: can repositories not be deleted once they've been added (like workspaces)? If not, should this be allowed. (I think it should? Odd to be able to add repositories but not remove them)

**Comment by filippomc** [comment]
Deletion was disabled thinking on the fact that in case they are linked to workpaces it would be tricky to do the cascade change. Reality is at the moment there is no hard link between a workspace and a repository once files are added, so in the case that link is not to come we can safely enable the deletion. An alternative would be to make a soft delete that just prevents the repo from appearing in the lists. 
As for the url and name, I think we can assume that changes are made with good intention, like because the repo was moved/renamed in the first place. That often happens after rebrandings.

**Comment by sanjayankur31** [comment]
Yeh, we'll have to think about it if we do have stronger links between repos and workspaces.

I'll document the modification bit, and I guess we can leave it as it is for the moment and tweak things if we see cases where it is being abused.
