### ISSUE TITLE
/opt/home not retaining files

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#395]
The /opy/home drive used to (I believe...) work as a place users could store files which would be accessible every session/workspace. This doesn't seem to work anymore on v2 or v2dev, files can be placed tehre, but they're gone the next session.

**Comment by filippomc** [comment]
The user workspace is not back on /opt/user as it was. Can change to /opt/home if desired (or maybe /mnt/user would be more linux conventions compliant)

**Comment by pgleeson** [comment]
Thanks. /opt/user is fine for now (unless you think /mnt/user would be better @sanjayankur31?) 

Note /opt/home is still there, which should be removed if it's not used for anything.

**Comment by sanjayankur31** [comment]
either work I guess, as long as we document it so that users know and don't change it once we have users on the platform. `/mnt/user` is probably more like what folks would have on their own machines? :thinking: 

I see we symlink `$HOME/workspace` to `/opt/workspace`. Is it worth adding a `$HOME/files` (or something like that) symlink there pointing to `/opt/user` or `/mnt/user` too and ask users to use that? Then the actual location of the files doesn't matter---we can use whatever we wish as long as the symlink is pointing to correct the location.
