### ISSUE TITLE
Workspace tabs/filtering styling: tabs get covered on narrower screens

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#419]
Even without the search, on narrow screens, the tabs tend to get lost on the right hand side of the screen:

![Screenshot 2022-03-24 at 10-36-09 Open Source Brain.png](https://images.zenhubusercontent.com/5ed7b344ccca35039a2f1aed/e84843ce-20ba-475c-bee4-ccd487f589bb)

With the search, this is more noticeable now:

![Screenshot 2022-03-24 at 10-34-39 Open Source Brain.png](https://images.zenhubusercontent.com/5ed7b344ccca35039a2f1aed/8925c0c7-87e5-4fd9-b934-e25fc613e876)

I think the styling needs to be tweaked so that as soon as the "public workspace" text stops fitting in the page, the whole right section goes down to a new row?

**Comment by sanjayankur31** [comment]
If I select "public workspaces" when there isn't enough space, the first tab goes missing:

![Screenshot 2022-03-24 at 10-41-15 Open Source Brain](https://user-images.githubusercontent.com/102575/159899134-4d35f900-13db-4bcc-a743-91b15aef06f7.png)

**Comment by sanjayankur31** [comment]
(Sort of why I'd added the search on a different line in the initial implementation---that way it didn't interfere with the tabs)

**Comment by filippomc** [comment]
The search by default is only one icon and the issue was there before that icon was there: I think that this is fine for now on narrower screens as the search is really a secondary element and it wouldn't be fair to take a consistent space in the interface. What we can easily do without rethinking everything is to limit the text with hypens on smaller screens. Let me see how it looks like

**Comment by filippomc** [comment]
fixed --  worst case now: ![image.png](https://images.zenhubusercontent.com/5c4f23c24557275e4b89d83b/bd4ea639-8ecc-4e5e-8b88-b08046f30f0b)
