### ISSUE TITLE
Repository URLs on DANDI are also storing their context, which breaks the "view on DANDI" link where the context is added again to the URL

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSBv2#445]
Example:

https://v2dev.opensourcebrain.org/repositories/13

The "view on DANDI" link should be: https://gui.dandiarchive.org/#/dandiset/000053/draft

but is https://gui.dandiarchive.org/#/dandiset/000053/draft/draft

because the repository URL has "draft" in it already. We should strip this context from the repository URL before saving this information

**Comment by zsinnema** [comment]
@pgleeson imo the repository url should be https://dandiarchive.org/dandiset/000053

the current repo url is pointing to a specific version of the dandiset named `draft` (https://dandiarchive.org/dandiset/000053/draft)

my suggestion here would be to show the "base" url of the dandiset in the page and not the "base" url + the default context (in this case draft)

the other option: stripping the context from the "entered" repositor url is not 100% safe (there could be a situation where we strip incorrect characters) instead of this I would recommend to put a kind of regular expression on the url input field so that for dandisets the url always matches `.../dandiset/<integer>`

@pgleeson what's you opinion about this?

**Comment by filippomc** [comment]
@zsinnema one option is to strip the 3rd element from the url in the frontend and use it as a version/context

**Comment by pgleeson** [comment]
The proposal we discussed today being that if a user enters a URL like:
https://dandiarchive.org/dandiset/000053/draft 
or
https://dandiarchive.org/dandiset/000053/0.210819.0345
into the new repository dialog, that it's automatically stripped to 
https://dandiarchive.org/dandiset/000053
and the selected branch/version is selected in the drop down box below. If any other url is used it should complain with an example fo correct url.
