### ISSUE TITLE
https broken for v1

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#731]
https://www.opensourcebrain.org and https://opensourcebrain.org give a security error. Perhaps related to the updates for www.v2....?

**Comment by sanjayankur31** [comment]
I can't open v1 in my browser at all because the certificate seems to have expired. I'll open an issue on our status website about this, but we need to please prioritise this and fix it ASAP @filippomc 

![20230425-osbv1-down](https://user-images.githubusercontent.com/102575/234246917-17ca3d6e-090c-48ca-bb62-0e78bcaed99e.png)

**Comment by sanjayankur31** [comment]
See also: https://github.com/OpenSourceBrain/ServiceStatus/issues/3

**Comment by pgleeson** [comment]
Yes, works for me too, thanks!
