### ISSUE TITLE
Deleting one resource resulted in whole folder being deleted

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#738]
To reproduce:
- create new workspace from: https://v2.opensourcebrain.org/repositories/38
- go to workspace page.
- delete one of the 3 nwb files in Workspace Resources panel
- refresh page - no NWB resources are shown
- open in JupyterLab - the whole NWB folder is gone

I tried also with deleting a notebook, it seemed to just delete that one, but I had problems opening the workspace in jupyterlab afterwards

**Comment by filippomc** [comment]
The bug is related on how resources are stored in the database. There is an assumption about the resource being identified by the folder containing it. This works for resources imported from the database and for the idea behing the netpyne format but it's clearly wrong in many other cases.

The way I propose to solve this is to change the resource model to change from {name, folder} to {name, path}, so we save the full path of the main resource file, which is the file itself for nwb and notebooks, the index file for netpyne models
